[project]
name = "instagram_bot"
version = "0.1.0"
description = "Instagram bot for flashcards and memes"
authors = [{ name = "Santhosh1933" }]
[tool.setuptools]
packages = [
    "image_generator",
    "instagram_uploader",
    "flashcard_generator",
    "meme_prompt_generator"
]