name: Instagram Bot Daily Runs

on:
  schedule:
    - cron: "0 7,13,19 * * *"
  workflow_dispatch:

jobs:
  run-bots:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      ANI_ACCESS_TOKEN: ${{ secrets.ANI_ACCESS_TOKEN }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      BUSINESS_ACCOUNT_ID: ${{ secrets.BUSINESS_ACCOUNT_ID }}
      ANI_BUSINESS_ACCOUNT_ID: ${{ secrets.ANI_BUSINESS_ACCOUNT_ID }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Animal image generator
        run: python animal_main.py

      - name: Run meme generator
        run: python meme_generator_main.py

      - name: Run flashcard generator
        run: python flashcard_main.py
